import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Nav from "../components/Nav/Nav";
import { useRouter } from "next/router";
import { useUser } from "../hooks/useUser";
import {useEffect} from "react";

export default function Home() {
    const [user] = useUser()
    const router = useRouter()

    useEffect(()=>{
        if (user) {
            router.push("home")
        }
    }, [user, router])

    return (<div className={styles.container}>
        <Head>
            <title>Pokemon Next App</title>
            <meta name="description" content="Pokemon App generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Nav/>
        <main className={styles.main}>

            <h1 className={styles.title}>
                Welcome to <a href="https://nextjs.org">Next.js!</a>
            </h1>

            <p className={styles.description}>
                Get started by editing{' '}
                <code className={styles.code}>pages/index.js</code>
            </p>

            <div className={styles.grid}>

            </div>

        </main>
        <footer className={styles.footer}>
            <p>Powered by Vercel</p>
        </footer>
    </div>)
}
